group:
  repos: |
    user/repo
    user/repo1
  files:
    # general files
    - .gitignore
    - LICENSE
    # build files
    - .github/workflows/create-debug-docs.yaml
    - .github/workflows/create-release-docs.yaml
    - .github/workflows/kibot-check.yaml
    - doc/_config.yml
    - doc/favicon.ico
    - doc/Icon.png
    - scripts/
    - Gemfile
    - production.kibot.yaml
    - test.kibot.yaml
