name: Create Production Data For Beta No-Release Version
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  export-ecad:
    name: Export ECAD
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update the PCBs with the BETA and git hash
        run: |
          export COMMIT=$(git rev-parse --short HEAD)
          echo "COMMIT = ${COMMIT}"
          sed -i "s/<<HASH>>/BETA-${COMMIT}/g" *.kicad_*

      - name: Generate Export Files
        uses: INTI-CMNB/KiBot@v2_k9
        with:
          config: output.kibot.yaml
          dir: output
          schema: main.kicad_sch
          board: main.kicad_pcb
          verbose: 0

      - name: Upload Export Files as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production
          path: output
          if-no-files-found: error
