name: Create Debug Docs
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    uses: OE5XRX/HW-Module-CI/.github/workflows/create-debug-docs.yaml@main
    secrets: inherit
