name: Create Production Data For Beta Version
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  export-ecad:
    name: Export ECAD
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update the PCBs with the BETA and git hash
        run: |
          export COMMIT=$(git rev-parse --short HEAD)
          echo "COMMIT = ${COMMIT}"
          sed -i "s/<<HASH>>/BETA-${COMMIT}/g" *.kicad_*

      - name: Generate Export Files
        uses: INTI-CMNB/KiBot@v2_k9
        with:
          config: production.kibot.yaml
          dir: output
          schema: main.kicad_sch
          board: main.kicad_pcb
          verbose: 0

      - name: Upload Export Files as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production
          path: output
          if-no-files-found: error


  collect-and-provide:
    runs-on: ubuntu-24.04
    needs: export-ecad
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
        with:
          generator_config_file: doc

      - name: Build with Jekyll
        run:  cd doc && bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - uses: actions/download-artifact@v5
        with:
          name: production
          path: doc/_site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: doc/_site
          target-folder: ${{ env.DEPLOY_PATH }}
          clean: true
